/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructure;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.List;

/**
 *  Class Name      : GraphElement
 *  Created Date    : 2015-07-23
 *  Description     : A Graph Element can be a Node or Edge
 *  Version         : 1.0
 *  @author         : Talat
 * 
 *  EDIT HISTORY (most recent at the top)
 *  Date            Author          Description
 *  
 * 
*/
public class GraphElement {
    
    /* VARIABLES */
    private int intElementType; // 0 for Nodes and 1 for Edges
    private int intMeerkatID; // ID generated by Meerkat
    private List<AbstractMap.SimpleEntry> lstkvpAttributes ; // List of KeyValue Pairs where Key is the Attribute Name and Value is the Attribute Value
    
    /* GETTERS AND SETTERS */
    public int getElementType() {
        return this.intElementType;
    }
    public int getMeerkatID() {
        return this.intMeerkatID;
    }
    public List<AbstractMap.SimpleEntry> getAttributes() {
        return this.lstkvpAttributes;
    }
    public void addAttribute(String pstrKey, String pstrValue) {
        this.lstkvpAttributes.add(new AbstractMap.SimpleEntry(pstrKey, pstrValue));
    }
    public void addattributes( List<AbstractMap.SimpleEntry> plstkvpAttributes) {
        this.lstkvpAttributes.addAll(plstkvpAttributes);
    }
    
    /* CONSTRUCTORS */
    public GraphElement() {
        lstkvpAttributes = new ArrayList<>();
    }
    public GraphElement(int pintElementType, int pintMeerkatID, List<AbstractMap.SimpleEntry> plstkvpAttributes) {
        this();
        this.intElementType = pintElementType;
        this.intMeerkatID = pintMeerkatID;
        this.lstkvpAttributes.addAll(plstkvpAttributes);
    }
}
